apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: transportadora-app:1.1
          ports:
            - containerPort: 8000
          env:
            - name: PS_DATABASE_URL
              value: postgresql://admin:admin@localhost:5432
          envFrom:
          - configMapRef:
              name: postgres-config
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 200Mi    
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  type: ExternalName
  externalName: localhost
