apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-container
        image: rabbitmq:3.10-management
        ports:
        -   
          name: rabbitmq-server
          containerPort: 5672
        -
          name: rabbitmq-mgm
          containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    -
      name: "rabbitmq-server"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
    -
      name: "rabbitmq-server-mgm"
      protocol: "TCP"
      port: 15672
      targetPort: 15672
  type: LoadBalancer
---
#apiVersion: "v1"
#kind: "Endpoints"
#metadata:
#  name: "rabbitmq-endpoint"
#subsets:
#  -
#    addresses:
#      -
#        ip: "10.128.0.27"
#    ports:
#      -
#        port: 5672
#        name: "rabbitmq-server"
#      - 
#        port: 15672
#        name: "rabbitmq-mgm"