apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq-container
    image: rabbitmq:3.10-management
    ports:
    - containerPort: 5672
    - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    -
      name: "rabbitmq-server"
      protocol: "TCP"
      port: 5672
      targetPort: 5672
    -
      name: "rabbitmq-server-mgm"
      protocol: "TCP"
      port: 15672
      targetPort: 15672
  type: LoadBalancer